name: io_photobooth
description: BXS Photo Booth app.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.1
#  flutter: 3.8.0-14.0.pre.10

dependencies:
  analytics:
    path: packages/analytics

  authentication_repository:
    path: packages/authentication_repository

  bloc: ^9.0.0

  camera:
    path: packages/camera/camera

  cross_file: ^0.3.4+2
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0

  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter

  image_compositor:
    path: packages/image_compositor

  intl: ^0.20.2
  just_audio: ^0.9.31

  photobooth_ui:
    path: packages/photobooth_ui
  photos_repository:
    path: packages/photos_repository
  platform_helper:
    path: packages/platform_helper

  rxdart: ^0.28.0
  uuid: ^4.5.1
  very_good_analysis: ^9.0.0

dev_dependencies:
  bloc_test: ^10.0.0

  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  plugin_platform_interface: ^2.1.8
  test: ^1.21.7
  url_launcher_platform_interface: ^2.3.2

#dependency_overrides:
#  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
    - assets/backgrounds/
    - assets/images/
    - assets/icons/
    - assets/props/dorco/
    - assets/props/google/
    - assets/props/hats/
    - assets/props/eyewear/
    - assets/props/food/
    - assets/props/shapes/
