// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // projectId: 'dorco-retail-event',
    // appId: '1:305924165949:web:d88b298b8aaf7bfc96b554',
    // apiKey: 'AIzaSyAERZxMnQYNnmwjVI1Nujfn9vlwpfZzI3s',
    // storageBucket: 'dorco-retail-event.firebasestorage.app',
    // authDomain: 'dorco-retail-event.firebaseapp.com',
    // messagingSenderId: '305924165949',
    apiKey: 'AIzaSyBKy80SCh6HJcdJfDr1IqmhaXHlbC5Q6NE',
    appId: '1:305924165949:web:0b99b140e37a311096b554',
    messagingSenderId: '305924165949',
    projectId: 'dorco-retail-event',
    authDomain: 'dorco-retail-event.firebaseapp.com',
    storageBucket: 'dorco-retail-event.firebasestorage.app',
  );
}
